/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package aulajavafx;

import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.control.Label;
import javafx.scene.layout.StackPane;
import javafx.scene.layout.VBox;
import javafx.stage.Stage;
import javafx.scene.Parent; 


public class App extends Application {

    @Override
    public void start(Stage stage) {
        Scene scene = new LoginScene (new VBox(), 640, 480);
        stage.setScene(scene);
        stage.show();
    }

    public static void main(String[] args) {
        launch();
    }

}
