/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Corrida;

public class App {
        public static void main(String[] args) {
            Veiculo fusca= new Veiculo(new MotorFusca());
            Veiculo ferrari= new Veiculo (new MotorFerrari());
            Veiculo lamborghini = new Veiculo(new MotorLamborghini());
            Veiculo corsa = new Veiculo(new MotorCorsa());
            System.out.println(fusca.acelerar());
            System.out.println(corsa.acelerar());
            System.out.println(ferrari.acelerar());
            System.out.println(lamborghini.acelerar());
    }
}




