/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package StreetFighter;

public class App {
   public static void main(String[] args) {
       Time orochi = new Time();
       Time ikariWarriors = new Time();
       
       
  
  ikariWarriors.l1 = new Personagem(new ComandoRalf(), "Ralf", 23);
  ikariWarriors.l2 = new Personagem(new ComandoClark(), "Clark", 23);
  ikariWarriors.l3 = new Personagem(new ComandoLeona(), "Leona", 21);
  
  
  orochi.l1 = new Personagem(new ComandoIori(), "Iori", 19);
  orochi.l2 = new Personagem(new ComandoMature(), "Mature", 22);
  orochi.l3 = new Personagem(new ComandoVice(), "Vice", 25);

  System.out.println("ROUND 1 --------- START!!!");
  System.out.println(orochi.l1.golpe());
  System.out.println(ikariWarriors.l1.golpe());
  System.out.println("IORI WINS!!!");
  
  System.out.println("ROUND 2 --------- START!!!");
  System.out.println(orochi.l2.golpe());
  System.out.println(ikariWarriors.l2.golpe());
   System.out.println("CLARK WINS!!!");
  
  System.out.println("ROUND 3 --------- START!!!");
  System.out.println(orochi.l3.golpe());
  System.out.println(ikariWarriors.l3.golpe());
  System.out.println("VICE WINS!!!");
    }
 }

